export const MENU_ITEMS = {
  lunch: {
    bites: [
      { label: `Spiced Peanuts`, price:10 },
      { label: `Pickles`, price:4 },
      { label: `Mushroom Hor Mok`, price:14 },
      { label: `Som Tum Papaya Salad`, price:10 },
      { label: `Pretty Hot Wings`, price:12 },
      { label: `Nam Tok Beans`, price:14 },
      { label: `Stir-Fried Baby Choy Sum`, price:9 },
    ],
    eats: [
      { label: `Khao Mun Gai `,price:16},
      { label: `Crispy Chicken Sandwich `,price:13},
      { label: `Bangkok Posh Salad `,price:14},
      { label: `Ngop Pla `,price:16},
      { label: `Yaowaraj Noodle `,price:16},
      { label: `Khao Soi `,price:16},
      { label: `The Pork Bowl `,price:16},
    ],
    dessert: [
      { label: `Black Rice Pudding`, price: 12}
    ],
    sides: [
      { label: `Sticky rice`,price: 4 },
      { label: `White rice`,price: 4 },
      { label: `Chicken Broth`,price: 4 },
    ],
  },
  dinner: {
    bites: [
      { label: `Pork Cracklings`,price: 7 },
      { label: `Spiced Peanuts`,price: 7 },
      { label: `Pickles`,price: 4 },
      { label: `Mushroom Hor Mok`,price: 14 },
      { label: `Yum Som-O`,price: 15 },
      { label: `Nam Tok Beans`,price: 14 },
      { label: `Pretty Hot Wings`,price: 12 },
    ],
    meats: [
      { label: `Caramelized Pork Belly`,price:17},
      { label: `Laab Kua`,price:16},
      { label: `Yaowaraj Noodle`,price:19},
    ],
    fish_seafood: [
      { label: `Plah Pla Muek`, price: 16 }
    ],
      namprik_relish: [
      { label: `Namprik Long Rua`, price: 27 }
    ],
    greens: [
      { label: `Khao Yum`, price: 15 },
      { label: `Stir-Fried Baby Choy Sum`, price: 9 },
    ],
    curries: [
      { label: `Massaman Nuea`,price:35},
      { label: `Khun Yai’s Rabbit Green Curry`,price:35},
      { label: `Butternut Squash Panang`,price:35},
    ],
    sides: [
      { label: `Sticky rice`,price: 4 },
      { label: `Brown Jasmine Rice`, price: 4},
      { label: `White rice`,price: 4 },
      { label: `Chicken Broth`,price: 4 },
      { label: `Salted Duck Egg`, price: 4}
    ],
  },
  spacials: {
    prix_fixe: [
      { label: `Friends and Family Menu`, price: 65 }
    ]
  },
  drinks: {
    cocktails: [
      { label: `Hua Hin Beach`, price:13},
      { label: `Pak Pow`, price:13},
      { label: `Rasa Umami`, price:13},
      { label: `Farang 75`, price:13},
      { label: `Komut`, price:13},
      { label: `Kathoey Collins`, price:13},
      { label: `Siam Sipper`, price:13},
      { label: `Pattaya Shake`, price:13},
      { label: `Tom Yum`, price:13},
      { label: `Kem Kon`, price:13},
      { label: `My Thai`, price:13},
      { label: `The Artist's Reward`, price:13}
    ],
    sparkling: [
      { label: `nv egly-ouriet grand cru extra brut “viellissement prolongÉ”`, price: 166 },
      { label: `nv de montbourgeau “l’etoile” crémant du jura`, price: 70 },
      { label: `mv billecart-salmon brut Rosé`, price: 162 }
    ],
    white_rose: [
      { label: `'17 domaine de marquiliani Rosé gris`, price: 60 },
      { label: `‘16 do ferreiro Albariño`, price: 58 },
      { label: `'15 paolo bea “santa chiara”`, price: 90 },
      { label: `'17 ameztoi “getariako txakolina”`, price: 60 },
      { label: `'15 francois rousset-martin
      “memee marie”`, price: 84 },
      { label: `‘14 huet “clos du bourg”
      demi-sec vouvray`, price: 120} 
    ],
    agave: [
      { label: `Fortaleza Blanco`,price:10},
      { label: `Fortaleza Reposado`,price:12},
      { label: `Fortaleza Anejo`,price:15},
      { label: `Tequila Ocho Plata`,price:10},
      { label: `Tequila Ocho Reposado`,price:12},
      { label: `Tequila Ocho anejo`,price:15},
      { label: `Mezcal vago espadin`,price:14},
      { label: `derrumbes san luis potosi mezcal`,price:14},
      { label: `nuestra soledad san baltazar guelavila mezcal`,price:14},
      { label: `yuu baal pechuga`,price:19},
      { label: `montelobos`,price: 9},
      { label: `por siempre sotol`,price:12},
    ],
    brandy: [
      { label: `argonaut saloon strength`, price:10},
      { label: `arkansas straight applejack`, price:12},
      { label: `barsol pisco quebranta`, price: 9},
      { label: `Delamain XO`, price:20},
      { label: `frapin xo`, price:30},
      { label: `germain-robin craft method brandy`, price:15},
      { label: `Pierre Ferrand 1840`, price:11},
    ],
    digestif_amaro: [
      { label: `Alta verde assenszio`,price: 9},
      { label: `Amaro Montenegro`,price:10},
      { label: ` Amaro Zucca Rabarbaro`,price: 9},
      { label: `Amaro Averna`,price: 9},
      { label: `cardamaro vino amaro`,price: 9},
      { label: `Cynar`,price: 9},
      { label: `falcon spirits aplomado`,price:10},
      { label: `Fernet Branca`,price: 8},
      { label: `pasubio vino amaro`,price: 9},
      { label: `paolucci amaro ciocaro`,price: 9},
      { label: `r. Jelinek fernet`,price: 8},
      { label: `amaro nonino quintessentia`,price:11},
    ],
    liqueur: [
      { label: `Benedictine`, price:12},
      { label: `Chartreuse Green`, price:12},
      { label: `Chartreuse Yellow`, price:12},
      { label: `Drambuie`, price:12},
      { label: `Luxardo Amaretto`, price: 9},
      { label: `luxardo maraschino`, price: 9},
      { label: `Pimms`, price: 9},
    ],
    aperitif_vermouth: [
      { label: `Aperol`, price: 9},
      { label: `Bonal`, price: 9},
      { label: `Campari`, price: 9},
      { label: `cap rock organic colorado bitter`, price: 9},
      { label: `Cappelletti`, price: 9},
      { label: `byrrh`, price: 8},
      { label: `Carpano Antica Formula Vermouth`, price: 8},
      { label: `lillet blanc`, price: 8},
      { label: `Cocchi Americano`, price: 8},
      { label: `Cocchi Rosa`, price: 8},
      { label: `cocchi torino`,  price:10},
      { label: `Dolin Dry Vermouth`, price: 8},
      { label: `Dolin Blanc Vermouth`, price: 8},
      { label: `Hammer & Tongs L’Afrique Vermouth`, price:10},
      { label: `lo-fI dry vermouth`, price: 8},
      { label: `Noilly Prat Dry Vermouth`, price: 8},
      { label: `Punt E Mes`, price: 8},
      { label: `Suze`, price: 9},
      { label: `Tempus Fugit Kina L’Avion D’Or`, price:10},
      { label: `Tempus Fugit Gran Classico`, price:10},
    ],
    sherry: [
      { label: `la cigarrera manzanilla`, price: 7},
      { label: `el maestro sierra 12 yr amontillado`, price: 13},
      { label: `cesar fLorido “cruz del mar” cream`, price: 10},
    ],
    vodka: [
      { label: `idaho G`,price: 9 },
      { label: `Tito’s`,price:10 },
      { label: `ketel one`,price:11 },
    ],
    gin: [
      { label: `automatic sea gin`, price:12 },
      { label: `barr hill tom cat`, price:15 },
      { label: `Bols Genever`, price:10 },
      { label: `bols 100% malt genever`, price:15 },
      { label: `City of London`, price: 9 },
      { label: `gray whale gin`, price:12 },
      { label: `hayman’s old tom`, price: 9 },
      { label: `Hendrick’s`, price:12 },
      { label: `nikka coffey still`, price:13 },
      { label: `plymouth`, price:10 },
      { label: `St. George ‘botanivore’`, price:10 },
      { label: `Tanqueray`, price: 9 },
      { label: `uncle val’s restorative gin`, price:12 },
      { label: `royal dock navy strength`, price: 9 },
      { label: `no. 209`, price:10 },
    ],
    whiskey: [
      { label: `dickel rye`, price: 9 },
      { label: `redemption rye`, price:10 },
      { label: `high west double rye`, price:13 },
      { label: `Michters Single Barrel Rye`, price:11 },
      { label: `Rittenhouse Bonded`, price: 9 },
      { label: `Mellow Corn`, price: 7 },
      { label: `Elijah craig Small batch`, price:11 },
      { label: `Four Roses Yellow Label`, price: 9 },
      { label: `Johnny Drum Private Stock`, price:12 },
      { label: `Maker’s Mark cask strength`, price:11 },
      { label: `Michters Small Batch Bourbon`, price:11 },
      { label: `Old Grandad bonded`, price: 9 },
      { label: `traverse city cherry bourbon`, price:14 },
      { label: `Wild Turkey 101`, price: 9 },
      { label: `pure kentucky`, price:14 },
      { label: `george dickel barrel select`, price:13 },
      { label: `george dickel no 8`, price: 9 },
      { label: `Jameson`, price: 9 },
      { label: `High West CampFIre`, price: 13 },
    ],
    whisky: [
      { label: `Johnnie Walker Black Label`, price:12 },
      { label: `Royal Salute 21 yr`, price:45 },
      { label: `Compass Box Oak Cross`, price:15 },
      { label: `Ardbeg 10 yr`, price:14 },
      { label: `Highland Park 18 yr`, price:22 },
      { label: `glenfIddich 14 yr bourbon barrel aged`, price:11 },
      { label: `Glenlivet 12 yr`, price:14 },
      { label: `Lagavulin 16 yr`, price:15 },
      { label: `Macallan 12 yr`, price:15 },
      { label: `macallan 18 yr`, price:40 },
      { label: `Talisker Distiller’s Edition 18 yr`, price:17 },
      { label: `balvenie caribbean cask`, price:16 },
      { label: `Nikka taketsuru`, price:14 },
      { label: `wayward whiskey single malt`, price:13 },
      { label: `Westland american oak`, price: 14 }
    ],
    cane: [
      { label: `Batavia Arrack van Oosten`, price: 9 },
      { label: `cadenhead guyana rum 11yr`, price:17 },
      { label: `cadenhead haiti 9yr`, price:13 },
      { label: `Denizen`, price: 9 },
      { label: `Denizen Merchant’s reserve 8yr`, price:12 },
      { label: `Plantation 5yr`, price:10 },
      { label: `plantation 20yr anniversary`, price:13 },
      { label: `plantation pineapple rum`, price:13 },
      { label: `rhum jm blanc`, price:11 },
      { label: `ron zacapa 23 rum`, price:13 },
      { label: `Sailor Jerry`, price: 9 },
      { label: `Smith and Cross`, price: 9 },
      { label: `avua amburana cachaÇa`, price:13 },
      { label: `avua prata cachaÇa`, price: 11 },
    ]
  }
};